matrix:
  - name: Markdown
    aspell:
      lang: en
    dictionary:
      wordlists:
        - spellcheck-wordlist.txt
    pipeline:
      - pyspelling.filters.text:
          normalize: nfd
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - "**/*.md"
    default_encoding: utf-8
